# Generated by Django 6.0.3 on 2026-03-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secrets_manager', '0006_remove_frequence_rotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('renouvele_le', models.DateTimeField(auto_now=True)),
                ('conteneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_acces', to='secrets_manager.conteneursecret')),
            ],
        ),
    ]
