# Generated by Django 6.0.3 on 2026-03-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_app', models.CharField(max_length=255)),
                ('nom_app', models.CharField(max_length=255)),
                ('password_app', models.CharField(max_length=255)),
                ('description_app', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.CharField(max_length=255, unique=True)),
                ('nom_projet', models.CharField(max_length=255)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='apps_manager.application')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projet',
            },
        ),
    ]
