# Generated by Django 6.0.3 on 2026-03-16 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteneurSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_conteneur', models.CharField(max_length=255)),
                ('type_conteneur', models.CharField(max_length=100)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('date_expiration', models.DateTimeField()),
                ('frequence_rotation', models.IntegerField(default=30, help_text='Fréquence en jours')),
                ('delai_anticipation', models.IntegerField(default=7, help_text='Alerte X jours avant')),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('domaine_app', models.CharField(blank=True, max_length=255, null=True)),
                ('csr', models.TextField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteneur', to='apps_manager.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_secret', models.CharField(max_length=255)),
                ('type_secret', models.CharField(max_length=100)),
                ('type_contenu_secret', models.CharField(max_length=100)),
                ('ref_secret', models.CharField(help_text='UUID ou URI Barbican', max_length=255, unique=True)),
                ('conteneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='secrets_manager.conteneursecret')),
            ],
        ),
    ]
