# Generated by Django 6.0.3 on 2026-03-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteneursecret',
            name='csr',
        ),
        migrations.RemoveField(
            model_name='conteneursecret',
            name='renouvellement_auto',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='type_contenu_secret',
        ),
        migrations.AddField(
            model_name='conteneursecret',
            name='ref_new_conteneur',
            field=models.CharField(blank=True, help_text='UUID ou URI Barbican', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='conteneursecret',
            name='ref_old_conteneur',
            field=models.CharField(help_text='UUID ou URI Barbican', max_length=255, null=True, unique=True),
        ),
    ]
