# Generated by Django 6.0.3 on 2026-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_manager', '0002_remove_conteneursecret_csr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneursecret',
            name='ref_new_conteneur',
            field=models.CharField(blank=True, help_text='UUID ou URI Barbican', max_length=255, null=True, unique=True),
        ),
    ]
