# Generated by Django 6.0.3 on 2026-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_manager', '0003_fix_ref_new_conteneur_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneursecret',
            name='duree_validite',
            field=models.IntegerField(blank=True, help_text='Durée de validité en jours', null=True),
        ),
    ]
