"""
Django settings for BarbiLink project. 

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from django.contrib.messages import constants as messages_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#-- Nouveaux ajouts
# Dit à Python : "Regarde aussi à l'intérieur du dossier applications"
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Charge le fichier .env
load_dotenv()

# Durée d'inactivité en secondes (ex: 300s = 5 minutes)
#SESSION_COOKIE_AGE = 30  

# Ferme la session dès que l'utilisateur ferme son navigateur
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True  

# Indispensable : remet le compteur à zéro à chaque clic (activité)
#SESSION_SAVE_EVERY_REQUEST = True

LOGIN_URL = '/'


# Mapping des niveaux de messages vers les classes Bootstrap
MESSAGE_TAGS = {
    messages_constants.ERROR: 'danger',
}

# Intervalle de vérification du renouvellement automatique (en secondes)
AUTO_RENEWAL_INTERVAL = 86400  # 1 jour

# Chemin vers la CA interne 
CA_CERT_PATH = os.path.join(BASE_DIR, 'BarbiLink', 'CA_OpenSSL', 'certificat', 'ssl-cert-snakeoil.pem')
CA_KEY_PATH = os.path.join(BASE_DIR, 'BarbiLink', 'CA_OpenSSL', 'cle', 'ssl-cert-snakeoil.key')

# Chemin vers ton dossier de logs
LOG_DIR = BASE_DIR / "logs"

# Crée le dossier s'il n'existe pas
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Configuration du logging des erreurs
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} : {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "fichier": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, 'secrets_manager.log'),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "secrets_manager": {        # ← nom de ton app
            "handlers": ["console", "fichier"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}



# Récupère les variables d'environnement de KEYSTONE
KEYSTONE_URL = os.getenv('KEYSTONE_URL')
KEYSTONE_ADMIN_USERNAME = os.getenv('KEYSTONE_ADMIN_USERNAME')
KEYSTONE_ADMIN_PASSWORD = os.getenv('KEYSTONE_ADMIN_PASSWORD')
KEYSTONE_ADMIN_PROJECT = os.getenv('KEYSTONE_ADMIN_PROJECT')
KEYSTONE_ADMIN_DOMAIN = os.getenv('KEYSTONE_ADMIN_DOMAIN')

# Recupere les variables d'environnement de BARBICAN
BARBICAN_URL = os.getenv('BARBICAN_URL')
BARBICAN_USERNAME = os.getenv('BARBICAN_USERNAME')
BARBICAN_PASSWORD = os.getenv('BARBICAN_PASSWORD')
BARBICAN_PROJECT = os.getenv('BARBICAN_PROJECT')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0h^gni4(qmsjrwk(j+$_fe7#vf4mr4*eon%r0c#kms-izc-&pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['192.168.100.251', 'localhost', '127.0.0.1']

# Definition de notre model user
AUTH_USER_MODEL = 'accounts.Utilisateur'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #-- Nouveaux ajouts
    'accounts',
    'crispy_forms',
    'crispy_bootstrap5',
    'apps_manager',
    'secrets_manager',
    'api_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #-- Nouveaux ajouts
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'BarbiLink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #-- Nouvel ajout
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BarbiLink.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr' #-- Modification faite 

TIME_ZONE = 'Africa/Douala' #-- Modification faite 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#-- Nouveaux ajouts
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Les templates pour le signalement automatique des erreurs.
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ── Configuration email (Gmail avec App Password) ──────────────────────────
EMAIL_BACKEND   = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST      = 'smtp.gmail.com'
EMAIL_PORT      = 587
EMAIL_USE_TLS   = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')      # ex: barbilink.app@gmail.com
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # App Password Gmail (16 chars)
DEFAULT_FROM_EMAIL  = os.getenv('EMAIL_HOST_USER', 'BarbiLink <barbilink.app@gmail.com>')